baseURL = "https://pixegon.com/"
languageCode = "en-us"
paginate = 7
theme = "portio"
title = "Albuquerque App Developer | Pixegon"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Services"
url = "#service"
weight = 3
# [[menu.main]]
# name = "Works"
# url = "#portfolio"
# weight = 4
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 8

# Sitemap Menu
[[menu.sitemap]]
name = "About us"
url = "/#about"
weight = 1
[[menu.sitemap]]
name = "Privacy Policy"
url = "/privacy"
weight = 3

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Pixegon Inc. 2023"
footerLogo = "images/site-navigation/pix-white.png"
#googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Corrales, New Mexico, USA"
email = "support@pixegon.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "+1 (505) 750-8732"

[params.map]
# APIkey = "YOUR GOOGLE MAP API"
# latitude = "23.7783741"
# longitude = "90.3746808"
# pinImage = "images/pin.png"

# Social icons
# [[params.social]]
# icon = "fa-facebook-official"
# url = "https://www.facebook.com/"
# weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/company/3866162"
weight = 2
# [[params.social]]
# icon = "fa-pinterest-square"
# url = "https://www.pinterest.com/"
# weight = 3
# [[params.social]]
# icon = "fa-twitter-square"
# url = "https://twitter.com/"
# weight = 4
